name: humanizer
description: A library to convert Dart values into human-friendly representations.
version: 2.2.0
repository: https://github.com/kentcb/humanizer

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  decimal: ^2.1.0
  intl: ^0.19.0
  meta: ^1.3.0
  rational: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.1
